//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int bid_ID { get; set; }
        public System.DateTime Time { get; set; }
        public double Price { get; set; }
        public Nullable<int> cus_ID { get; set; }
        public Nullable<int> pro_ID { get; set; }
        public Nullable<int> au_ID { get; set; }
    
        public virtual REL_Pro_Au REL_Pro_Au { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
