//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int im_ID { get; set; }
        public byte[] Img { get; set; }
        public Nullable<int> pro_ID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
