//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int re_ID { get; set; }
        public int Star { get; set; }
        public string Review1 { get; set; }
        public Nullable<int> or_ID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
